Add some select math functions & constants to `float'
With this, usercode gets access to `float.inf', and `float.nan', `float.isinf', `float.isnan', and a whole of buch of other functions.

Note that many of these were already available via the `math' dex, but this commit makes them available via object attributes. - Additionally, `int' also implements many of the same attributes, making it easy to write code that works with both float and int.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -846,6 +846,11 @@ try_compile_raw() {
 		-c -o "$CONFTEST_OUT" "$CONFTEST" >> "$CONFIG_LOG" 2>&1
 	return $?
 }
+try_compile_minimal() {
+	echo "exec: $CONFIG_CC $CONFIG_CFLAGS -Werror -c -o $CONFTEST_OUT $CONFTEST" >> "$CONFIG_LOG"
+	"$CONFIG_CC" $CONFIG_CFLAGS -Werror -c -o "$CONFTEST_OUT" "$CONFTEST" >> "$CONFIG_LOG" 2>&1
+	return $?
+}
 
 # e.g. try_check_feature "STDIO_H" "header <$1>"
 try_check_feature() {
@@ -1121,6 +1126,48 @@ EOF
 	check_ffi_cc FFI_GNUW64
 	check_ffi_cc FFI_EFI64
 fi
+
+
+# ieee754 detection trick stolen from autoconf
+echo -n "[?] Checking for ieee754..."
+echo "Checking for ieee754..." >> "$CONFIG_LOG"
+cat > "$CONFTEST" <<EOF
+double d = 90904234967036810337470478905505011476211692735615632014797120844053488865816695273723469097858056257517020191247487429516932130503560650002327564517570778480236724525140520121371739201496540132640109977779420565776568942592.0;
+EOF
+if try_compile_minimal; then
+	echo "#define CONFIG_HAVE_FPU 1" >> "$CONFINC"
+	if grep "seesnoon" "$CONFTEST_OUT" > /dev/null 2>&1; then
+		echo -e "\r[+] Checking for ieee754... (little-endian)"
+		echo "Checking for ieee754... little-endian" >> "$CONFIG_LOG"
+		echo "#define CONFIG_HAVE_IEEE754 1" >> "$CONFINC"
+		echo "#define CONFIG_HAVE_IEEE754_LE 1" >> "$CONFINC"
+	elif grep "noonsees" "$CONFTEST_OUT" > /dev/null 2>&1; then
+		echo -e "\r[+] Checking for ieee754... (big-endian)"
+		echo "Checking for ieee754... big-endian" >> "$CONFIG_LOG"
+		echo "#define CONFIG_HAVE_IEEE754 1" >> "$CONFINC"
+		echo "#define CONFIG_HAVE_IEEE754_BE 1" >> "$CONFINC"
+	else
+		echo -e "\r[-] Checking for ieee754... (no)"
+		echo "Checking for ieee754... no" >> "$CONFIG_LOG"
+		echo "#define CONFIG_NO_IEEE754 1" >> "$CONFINC"
+	fi
+else
+	echo "#define CONFIG_NO_IEEE754 1" >> "$CONFINC"
+	cat > "$CONFTEST" <<EOF
+double d = 0.0;
+EOF
+	if try_compile_minimal; then
+		echo -e "\r[-] Checking for ieee754... (no)"
+		echo "Checking for ieee754... no" >> "$CONFIG_LOG"
+		echo "#define CONFIG_HAVE_FPU 1" >> "$CONFINC"
+	else
+		echo -e "\r[-] Checking for ieee754... (no FPU support)"
+		echo "Checking for ieee754... no FPU support" >> "$CONFIG_LOG"
+		echo "#define CONFIG_NO_FPU 1" >> "$CONFINC"
+	fi
+fi
+
+
 
 unlink "$CONFTEST" > /dev/null 2>&1
 unlink "${CONFTEST_H}.gch" > /dev/null 2>&1
